name: Checksum Check
inputs:
  checksum-location:
    type: string
    required: true
    description: Location of the checksums that will be compared against
outputs:
  result:
    value: ${{ steps.check.outputs.result }}
    description: The result of the comparison between the artifact and the latest ground truth
  ground-truth-version:
    value: ${{ steps.ground-truth.outputs.version }}
    description: The ground truth version compared against the given artifact
runs:
  using: composite
  steps:
    - name: Fetch History and Determine Last Major Truth Update
      # By default, actions/checkout only checks out `--depth=1` (the tip of the main branch).
      # Even when we fetch tags the history is fragmented and usually isn't traversable from HEAD with `git describe --tags`.
      # We fetch the entirety of the main branch history to be able to do the next step, namely
      # traversing `main` to find the last `git tag` and suppresses the 'long form' of tags (that have a bunch of commit metadata).
      shell: bash
      # TODO: No need for unshallow when the repo is fully check out
      id: ground-truth
      run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

    - name: Compare Checksums between ${{ steps.ground-truth.outputs.version }} and ${{ inputs.config-tag }}
      shell: bash
      id: check
      run: |
        git diff --exit-code ..${{ steps.ground-truth.outputs.version }} CHECKSUM
        if [ "$?" -eq 0 ]; then
          echo "result=true" >> $GITHUB_OUTPUT
        else
          echo "result=false" >> $GITHUB_OUTPUT
        fi